name: alkhudhrah_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  easy_localization: ^3.0.0
  fancy_bottom_navigation: ^0.3.3
  flutter:
    sdk: flutter
  geolocator: ^8.0.1
  google_maps_flutter: ^2.0.9
  geocoding: ^2.0.1
  google_nav_bar: ^5.0.5
  json_annotation: any
  logger: any
  pin_code_fields: ^7.3.0
  retrofit: any
  shared_preferences: ^2.0.7-nullsafety
  flutter_pin_code_fields: ^1.1.0
  url_launcher: ^6.0.10
  font_awesome_flutter: ^9.2.0
  another_flushbar: ^1.10.28
  lottie: ^1.2.1
  flutter_slidable: ^1.2.0
  sliding_up_panel: ^2.0.0+1
  firebase_core: ^2.1.1
  firebase_dynamic_links: ^5.0.4
  flutter_local_notifications: ^9.3.2
  widget_mask: ^1.0.0
  firebase_messaging: ^14.0.4
  myfatoorah_flutter: ^2.1.5
  flutter_svg: ^1.0.3
  provider: ^6.0.2
  flutter_html_to_pdf: ^0.7.0
  device_info_plus: ^3.2.3
  infinite_scroll_pagination: ^3.2.0


dev_dependencies:
  build_runner: any
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  json_serializable: any
  retrofit_generator: any
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  image_path: 'assets/images/alkhadraa_app_icon_small.png'
  android: true
  ios: true
  remove_alpha_ios: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/locale/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: Almarai
    fonts:
      - asset: assets/fonts/Almarai-Regular.ttf


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
